Hackademic/hackademic

installation/sql/db.sql

Corrected a typo

---

assets/css/style.css
model/common/class.UserScore.php
user/plugins/challenge-clues/addchallenge.tpl
user/plugins/challenge-clues/challenge-clues.php
user/plugins/challenge-clues/class.Clue.php
user/plugins/challenge-clues/class.UserCluesModel.php
user/plugins/challenge-clues/editchallenge.tpl
user/plugins/challenge-clues/install-plugin.sql
user/plugins/challenge-clues/showChallenge.tpl

The new Clue plugin with a few clues for the 10 first challenges.
Btw, since my application I hesitate between clue and hint. Does clue seem right for the name? Should it be hint?

Clue plugin

---

init.php

Installation directory will be deleted once installation is over

---

locale/fr/french.pot

First go at the French translations.
We'll have to check that it does work (in particular the encoding :/) before we merge.

First French translations

---

assets/css/style.css

cosmetic one :) added some margins to login panel to give labels, inputs and button some air :)

cosmetic changes in login form style

---

assets/css/base.css
assets/css/style.css
view/register_user.tpl

just aligned inputs, labels and buttons properly and ad pointer/hand cursor when hovered on buttons - also added some bottom margin to main container not to be so sticky to bottom :)
tested on google chrome and firefox

aligning new user form

---

CONTRIBUTING.md
composer.json
development/scripts/PSR Compliance Pre Commit.php
development/scripts/PSR-1/ruleset.xml
development/scripts/PSR-2/Sniffs/Arrays/ArrayDeclarationSniff.php
development/scripts/PSR-2/Sniffs/Commenting/ClassCommentSniff.php
development/scripts/PSR-2/Sniffs/Commenting/FileCommentSniff.php
development/scripts/PSR-2/Sniffs/Commenting/InlineCommentSniff.php
development/scripts/PSR-2/Sniffs/Commenting/VariableComment.php
development/scripts/PSR-2/Sniffs/PHP/ForbiddenFunctionsSniff.php
development/scripts/PSR-2/Sniffs/Strings/ConcatenationSpacingSniff.php
development/scripts/PSR-2/ruleset.xml

* Added CodeSniffer sniff files for PSR 1 and 2
* Automate pre-commit execution of code sniffer and if necessary http://cs.sensiolabs.org/
* Updated the information on How Tos
* Added PHP Code Sniffer as requirement in composer.json.

Add sniff files and RuleSet for Stricter PSR 1 and 2 & Automate pre commit execution

---

.gitignore
.travis.yml
config.inc.php
hackademic_devtests/bootstrap.php
phpunit_mysql.xml

Added a concrete travis.yml file which sets up the platform for testing, a7044ae.
<del>How should I test this?</del>
I tested, it is working fine for one test case that @northdpole pushed. [Here](https://travis-ci.org/tapasweni-pathak/hackademic/jobs/78332494) is the success log. :smile: 
Let me know if I need to add something.
Please merge my previous PR first then this, as this is based on the fix_codesniffer_warnings branch, that will help me to avoid fixing merging issues. :) The changes that are coming are from previous PR. They will automatically go after the previous one is merged.

Add travis ci

---

admin/controller/class.EditUserController.php
admin/controller/class.UserManagerController.php
admin/view/usermanager.tpl

according <a href="https://github.com/Hackademic/hackademic/issues/111">this</a> I added hyperlink to activate user.

Add a button in User Manager to activate new users

---

ContainerManager/container_daemon.py
ContainerManager/hackademic-logs/install.logs
ContainerManager/logging_manager.py

Added run time exception handling 

---

ContainerManager/install.py
ContainerManager/logging_manager.py
ContainerManager/pip.txt

Fixed path issues in logging-manager.py and install.py

---

ContainerManager/Dockerfile

Removes proxy statement from Dockerfile

removes proxy statement from Dockerfile

---

ContainerManager/logging_manager.py

create logging directory if not exists

fixes bug in logging_manager

---

ContainerManager/README.md

changes `ip-address:1337/testchallenge1` to `ip-address:1337/samplechallenge`

modifies readme of ContainerManager

---

ContainerManager/README.md

adds steps to use Container Daemon

updates readme

---

ContainerManager/Web_Challenges/README.md
ContainerManager/Web_Challenges/samplechallenge/index.html
ContainerManager/Web_Challenges/staticfiles/css/style.css

Added necessary information for adding the challenges into README.

Made changes to README.md

---

challenges/ch041/.gitignore
challenges/ch041/Dockerfile
challenges/ch041/README
challenges/ch041/admin_simulate_job.js
challenges/ch041/index.php
challenges/ch041/run.sh
challenges/ch041/simulate_loop.sh

I have added session hijacking challenge. This uses a phantomjs cron job and I have created a Dockerfile.

Session hijacking challenge added.

---

challenges/ch041/.vagrant/README
challenges/ch041/Makefile
challenges/ch041/Vagrantfile
challenges/ch041/exp.py
challenges/ch041/vektor.c

Adds a simple binary challenge and a suggested solution.
I will update this PR with the article/tutorial as a write it.

Add binary challenge

---

challenges/izon/Dockerfile
challenges/izon/index.php
challenges/izon/login.php

Added docker file to create the image for izon challenge. The image needs to be created with command docker build -t chllg .
And then the container ports the challenge with the command:
docker run -d -p 80:80 -p 3306:3306 chllg

Dockerfile for izon challenge

---

behat.yml
composer.json
features/SolveChallenge.feature
features/Student.feature
features/bootstrap/FeatureContext.php

These functional tests are for Behat. Most of the function to perform various actions are already present in MinkContext class. Those which were not present were added explicitly. 
Things to note - 
1. Change the username and password depending on the user present in your database in SolveChallenge.feature file.
2. Behat along with Mink and Selenium is used. So, install them using composer(Composer.json is already updated).
3. To run the tests go to root of the project and type "php vendor/bin/behat"

Add Functional Tests

---

controller/class.RegisterUserController.php
model/common/class.Utils.php

There was an error if one of the fields is unset in registration form.

Register form validation

---

ContainerManager/container_daemon.py
ContainerManager/lettuce-tests/README.md
ContainerManager/lettuce-tests/features/create_container.feature
ContainerManager/lettuce-tests/features/kill_container.feature
ContainerManager/lettuce-tests/features/list_container.feature
ContainerManager/lettuce-tests/features/steps.py

Added some basic lettuce tests for docker sandbox and also included a bug fix for 'list_container functionality within the container daemon.

lettuce tests for docker sandbox plus a bugfix for 'list_container'

---

challenges/ch042/Dockerfile
challenges/ch042/README.md
challenges/ch042/app.py
challenges/ch042/requirements.txt
challenges/ch042/run.sh
challenges/ch042/static/css/normalize.css
challenges/ch042/static/css/skeleton.css
challenges/ch042/static/css/style.css
challenges/ch042/templates/base.html
challenges/ch042/templates/demo.html
challenges/ch042/templates/demo1.html
challenges/ch042/templates/demo2.html
challenges/ch042/templates/learn.html
challenges/ch042/templates/xss.html

Added firstcourse on XSS

---

esapi/src/codecs/Base64Codec.php

Make it compatible with php 7 by modifying encodeCharacter method

modifying encodeCharacter method

---

.travis.yml
development/scripts/PSR_COMPLIANCE_TRAVIS.php

Signed-off-by: spyros morfeas3000@gmail.com

Added tapasweni's coding standards checks to travis
